---
# 默认配置
server:
    address: 127.0.0.1
    port: 8082

---
# 开发配置
spring:
  profiles: development
server:
  address: 127.0.0.1
  port: 8080
logging:
  path: d:/logs


---
# 生产配置
spring:
  profiles: production
server:
  address: 192.168.1.120
  port: 80